name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        submodules: 'recursive'
    - name: Install build tools
      run: sudo apt update && sudo apt install -y cmake make
    - name: Build Flatc
      run: cd buildtools/flatbuffers && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release && make && sudo make install
    - name: Build with no features
      run: cargo build --no-default-features --verbose
    - name: Build with logging
      run: cargo build --features logging --verbose
    - name: Build with stats
      run: cargo build --features stats --verbose
    - name: Run tests with no features
      run: cargo test --no-default-features --verbose
    - name: Run tests with logging
      run: cargo test --features logging --verbose
    - name: Run tests with stats
      run: cargo test --features stats --verbose
    - name: Run clippy with no features
      run: cargo clippy --no-default-features
    - name: Run clippy with logging
      run: cargo clippy --features logging
    - name: Run clippy with stats
      run: cargo clippy --features stats

