name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        feature: [ "no-default-features", "logging", "stats" ]

    steps:
    - name: Detect if Dependabot
      id: is_dependabot
      run: |
        echo "is_dependabot=false" >> $GITHUB_OUTPUT
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is_dependabot=true" >> $GITHUB_OUTPUT
        fi

    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        token: ${{ steps.is_dependabot.outputs.is_dependabot == 'true' && secrets.GH_DEPENDABOT_PAT || secrets.GH_PAT }}
        submodules: recursive

    - name: Cache cargo registry and build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Get flatbuffers commit hash
      id: flatc_hash
      run: |
        cd buildtools/flatbuffers
        echo "flatc_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Cache Flatc build
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/flatc
        key: ${{ runner.os }}-flatc-${{ steps.flatc_hash.outputs.flatc_hash }}
            
    - name: Install build tools
      run: sudo apt update && sudo apt install -y cmake make

    - name: Build Flatc
      run: |
        if ! command -v flatc &> /dev/null; then
          cd buildtools/flatbuffers
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .
          make
          sudo make install
        else
          echo "Flatc already cached, skipping build."
        fi

    - name: Build ${{ github.repository }}
      run: |
        if [ "${{ matrix.feature }}" = "no-default-features" ]; then
          cargo build --no-default-features --verbose
        else
          cargo build --features ${{ matrix.feature }} --verbose
        fi

    - name: Test ${{ github.repository }}
      run: |
        if [ "${{ matrix.feature }}" = "no-default-features" ]; then
          cargo test --no-default-features --verbose
        else
          cargo test --features ${{ matrix.feature }} --verbose
        fi

    - name: Clippy ${{ github.repository }}
      run: |
        if [ "${{ matrix.feature }}" = "no-default-features" ]; then
          cargo clippy --no-default-features --all-targets -- -D warnings
        else
          cargo clippy --features ${{ matrix.feature }} --all-targets -- -D warnings
        fi
